"""add session and account tables

Revision ID: 067776139c4c
Revises: b494396a0dd7
Create Date: 2026-03-19 09:19:58.412192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067776139c4c'
down_revision: Union[str, Sequence[str], None] = 'b494396a0dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('accountId', sa.String(), nullable=False),
    sa.Column('providerId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('accessToken', sa.String(), nullable=True),
    sa.Column('refreshToken', sa.String(), nullable=True),
    sa.Column('idToken', sa.String(), nullable=True),
    sa.Column('accessTokenExpiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refreshTokenExpiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_userId', 'account', ['userId'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ipAddress', sa.String(), nullable=True),
    sa.Column('userAgent', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_session_userId', 'session', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_userId', table_name='session')
    op.drop_table('session')
    op.drop_index('ix_account_userId', table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
