"""add senha_hash to users

Revision ID: b494396a0dd7
Revises: 9f451b7a4ce8
Create Date: 2026-03-18 22:29:58.414740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b494396a0dd7'
down_revision: Union[str, Sequence[str], None] = '9f451b7a4ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senhaHash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'senhaHash')
    # ### end Alembic commands ###
